{% set name = "pylint-venv" %}
{% set version = "3.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: df12a17fca39a94acc1c9a0f1dcf68141e90fe685569d78c046695c67c4e55fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry-core >=1.0.0
  run:
    - python >=3.6

test:
  imports:
    - pylint_venv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jgosmann/pylint-venv/
  summary: pylint-venv provides a Pylint init-hook to use the same Pylint installation with different virtual environments.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ccordoba12
    - mwawra
